### PR TITLE
Fixes #512; fix strand color picker

### LINKED ISSUE #512: Cannot change staple color
Abstract: can't change staple color on  https://scadnano.org/dev/

How to reproduce:

1. Select any origami example on  https://scadnano.org/dev/
2. Right Click on a staple then "set color" then change the color then "OK"
3. The color doesnt change

I am using Chrome 1.0.4044.138

### PR DESCRIPTION
**Pull request by UnHumbleBen**
JS bindings were not setup properly so function name was not
recognized by dart2js compiled code

### CODE REVIEW

**Comment by UnHumbleBen** [comment]
After we merge to master, we should merge master to dev so that dev will also get this fix, as well as add version 0.12.2 to list of scadnano links

**Comment by UnHumbleBen** [comment]
I will also need to manually deploy v0.12,2 because the Github Actions for automatically deploying new versions have not been pushed to master yet.

File: lib/src/view/strand_color_picker.dart [hunk 1]
```diff
@@ -36,7 +40,7 @@ mixin StrandColorPickerState on UiState {
 
 class StrandColorPickerComponent
     extends UiStatefulComponent2<StrandColorPickerProps, StrandColorPickerState> {
-  void handleOnChangeComplete(color, event) {
+  void handleOnChangeComplete(JSColor color, event) {
```
Comment (dave-doty) [inline lib/src/view/strand_color_picker.dart:43]: If the event is not being used, better to name it `_`. (Also, do you know its type?)

**Review by dave-doty — CHANGES_REQUESTED** [review]

File: lib/src/view/strand_color_picker.dart (hunk 1 above)
Comment (UnHumbleBen) [reply lib/src/view/strand_color_picker.dart:43]: Not sure what type it event is. Here is the API: https://casesandberg.github.io/react-color/#api-onChangeComplete

**Review by dave-doty — APPROVED** [review]
